service: lesson4
app: lesson4

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1


  # you can define service wide environment variables here
  environment:
    PG_HOST: lesson4.cmlihsvlmgnc.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: lesson4
    PG_USERNAME: ${file(../db_creds.json):username}
    PG_PASSWORD: ${file(../db_creds.json):password}


functions:
  initDB:
    handler: pg-client-lambda.initDB
